# Generated by Django 4.0 on 2022-03-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufeed', '0002_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
