# Generated by Django 4.0 on 2022-03-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufeed', '0004_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='amount',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
